#define PALAVRA_RESERVADA 1
#define IDENTIFICADOR 2
#define IDENTIFICADOR_PADRAO 3
#define OPERADOR 4
#define OPERADOR_RELACIONAL 5
#define SIMBOLOS_OBRIGATORIOS 6
#define SIMBOLOS_ALTERNATIVOS 7
#define DECIMAL 8
#define OCTAL 9
#define HEXADECIMAL 10
#define OPERADOR_FACTOR 11
#define STRING 12
#define ONECARACTER 13







